repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 582b9c66e0791980685c8b80bb11e6a3df1a06ef
    hooks:
      - id: end-of-file-fixer
        exclude: "^dist"
      - id: trailing-whitespace
        exclude: "^dist"
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos
        exclude: "^dist"
